### PR TITLE
fix: Updated FIR1 filter in Python

### PR DESCRIPTION
**Pull request by guillemc23**
The used syntax is not valid, I implemented a minimal change on the `firwin` function to make it work. Not sure if it used to work with older versions of `scipy` but ti does definitely not work with the latest one 😄

### CODE REVIEW

**Comment by mikexcohen** [comment]
Hi guillemc. Thanks for posting about this! However, firwin still works with the original code when I tested it. I see you changed the frequency window to fraction of Nyquist, whereas I specified it in Hz and then provided an additional input fs= to specify the sampling rate (in Hz). Or specify Nyquist using nyq=

On colab, it works fine, and that runs scipy 1.13.1. Then I updated my colab session to 1.14.1 (the latest scipy version) and firwin still works using the code I ran. I also couldn't find any documentation online about this change (though perhaps I haven't looked enough).

Can you check your version of scipy, and perhaps give more details about what the issue is? e.g., an error message.

**Comment by guillemc23** [comment]
hi! I'm running Python 3.12.6 and `scipy` 0.14.1.

The code as is returns this error:
```
TypeError                                 Traceback (most recent call last)
Cell In[9], [line 7](vscode-notebook-cell:?execution_count=9&line=7)
      [3](vscode-notebook-cell:?execution_count=9&line=3) frange = [ 1000, 1100 ]
      [4](vscode-notebook-cell:?execution_count=9&line=4) # frange = [ 1200, 1450 ]
      [5](vscode-notebook-cell:?execution_count=9&line=5) 
      [6](vscode-notebook-cell:?execution_count=9&line=6) # design an FIR1 filter
----> [7](vscode-notebook-cell:?execution_count=9&line=7) fkern = signal.firwin(2001,frange,nyq=srate/2,pass_zero=False)
     [11](vscode-notebook-cell:?execution_count=9&line=11) # apply the filter to the signal
     [12](vscode-notebook-cell:?execution_count=9&line=12) filtglass = np.zeros(np.shape(glassclip))

TypeError: firwin() got an unexpected keyword argument 'nyq'
```

It just does not recognize `nyq` as an input argument.

What I did is try to fit it to the Matlab behavior:
```matlab
fkern = fir1(2001,frange/(srate/2),'bandpass');
```

These are the Scipy docs for the firwin function:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.firwin.html

Thank you!

**Comment by mikexcohen** [comment]
Ah, I see. fs= still works on v1.14.1 but they removed nyq= (that works on scipy 1.13.1). Quite annoying lack of backwards compatibility, though that's unfortunately normal for Python libraries... 

Anyway, I'll take your suggested fix. Thanks again for posting about this!

**Comment by guillemc23** [comment]
Definitely, way more common than it should be... thank you!
